Remove old gemfiles. Remove osx/internal/bin & ccache
- Developers should add gems themselves

diff --git a/osx/build-ruby b/osx/build-ruby
--- a/osx/build-ruby
+++ b/osx/build-ruby
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -ex
+set -e
 
 SELFDIR=`dirname "$0"`
 SELFDIR=`cd "$SELFDIR" && pwd`
@@ -22,19 +22,19 @@ COMPILE=true
 
 function _cleanup()
 {
-	if $OWNS_WORKDIR && [[ "$WORKDIR" != "" ]]; then
-		echo "Removing working directory $WORKDIR"
-		rm -rf "$WORKDIR"
-	fi
+  if $OWNS_WORKDIR && [[ "$WORKDIR" != "" ]]; then
+    echo "Removing working directory $WORKDIR"
+    rm -rf "$WORKDIR"
+  fi
 }
 
 function create_environment_file() {
-	local FILE="$1"
-	local LOAD_PATHS
+  local FILE="$1"
+  local LOAD_PATHS
 
-	LOAD_PATHS=`"$TMPBUILDROOT/bin.real/ruby" "$SELFDIR/../shared/dump-load-paths.rb" "$TMPBUILDROOT"`
+  LOAD_PATHS=`"$TMPBUILDROOT/bin.real/ruby" "$SELFDIR/../shared/dump-load-paths.rb" "$TMPBUILDROOT"`
 
-	cat > "$FILE" <<'EOF'
+  cat > "$FILE" <<'EOF'
 #!/bin/bash
 ROOT=`dirname "$0"`
 ROOT=`cd "$ROOT/.." && pwd`
@@ -50,10 +50,10 @@ echo TERMINFO=/usr/share/terminfo
 echo SSL_CERT_FILE=\"$ROOT/lib/ca-bundle.crt\"
 echo RUBYOPT=\"-r$ROOT/lib/restore_environment\"
 EOF
-	echo "echo GEM_HOME=\"\$ROOT/lib/ruby/gems/$RUBY_COMPAT_VERSION\"" >> "$FILE"
-	echo "echo GEM_PATH=\"\$ROOT/lib/ruby/gems/$RUBY_COMPAT_VERSION\"" >> "$FILE"
+  echo "echo GEM_HOME=\"\$ROOT/lib/ruby/gems/$RUBY_COMPAT_VERSION\"" >> "$FILE"
+  echo "echo GEM_PATH=\"\$ROOT/lib/ruby/gems/$RUBY_COMPAT_VERSION\"" >> "$FILE"
 
-	cat >> "$FILE" <<EOF
+  cat >> "$FILE" <<EOF
 echo RUBYLIB=\"$LOAD_PATHS\"
 
 echo export ORIG_DYLD_LIBRARY_PATH
@@ -73,144 +73,144 @@ echo export GEM_PATH
 echo export RUBYLIB
 EOF
 
-	chmod +x "$FILE"
+  chmod +x "$FILE"
 }
 
 function create_wrapper()
 {
-	local FILE="$1"
-	local NAME="$2"
-	local IS_RUBY_SCRIPT="$3"
+  local FILE="$1"
+  local NAME="$2"
+  local IS_RUBY_SCRIPT="$3"
 
-	cat > "$FILE" <<'EOF'
+  cat > "$FILE" <<'EOF'
 #!/bin/bash
 set -e
 ROOT=`dirname "$0"`
 ROOT=`cd "$ROOT/.." && pwd`
 eval "`\"$ROOT/bin/ruby_environment\"`"
 EOF
-	if $IS_RUBY_SCRIPT; then
-		cat >> "$FILE" <<EOF
+  if $IS_RUBY_SCRIPT; then
+    cat >> "$FILE" <<EOF
 exec "\$ROOT/bin.real/ruby" "\$ROOT/bin.real/$NAME" "\$@"
 EOF
-	else
-		cat >> "$FILE" <<EOF
+  else
+    cat >> "$FILE" <<EOF
 exec "\$ROOT/bin.real/$NAME" "\$@"
 EOF
-	fi
-	chmod +x "$FILE"
+  fi
+  chmod +x "$FILE"
 }
 
 function debug_shell()
 {
-	(
-		cd "$TMPBUILDROOT"
-		export PATH="$TMPBUILDROOT/bin:$PATH"
-		echo "Debug shell:"
-		sh
-	)
-	[[ $? == 0 ]]
+  (
+    cd "$TMPBUILDROOT"
+    export PATH="$TMPBUILDROOT/bin:$PATH"
+    echo "Debug shell:"
+    sh
+  )
+  [[ $? == 0 ]]
 }
 
 function usage()
 {
-	echo "Usage: ./build-ruby [options] <RUNTIME DIR> <OUTPUT DIR>"
-	echo "Build Traveling Ruby binaries."
-	echo
-	echo "Options:"
-	echo "  -E          Do not setup source"
-	echo "  -C          Do not compile Ruby"
-	echo "  -G          Do not install gems"
-	echo
-	echo "  -r VERSION  Ruby version to build. Default: $RUBY_VERSION"
-	echo "  -w DIR      Use the given working directory instead of creating a temporary one"
-	echo "  -j NUM      Compilation concurrency. Default: 4"
-	echo "  -g PATH     Build gems as specified by the given Gemfile"
-	echo "  -h          Show this help"
+  echo "Usage: ./build-ruby [options] <RUNTIME DIR> <OUTPUT DIR>"
+  echo "Build Traveling Ruby binaries."
+  echo
+  echo "Options:"
+  echo "  -E          Do not setup source"
+  echo "  -C          Do not compile Ruby"
+  echo "  -G          Do not install gems"
+  echo
+  echo "  -r VERSION  Ruby version to build. Default: $RUBY_VERSION"
+  echo "  -w DIR      Use the given working directory instead of creating a temporary one"
+  echo "  -j NUM      Compilation concurrency. Default: 4"
+  echo "  -g PATH     Build gems as specified by the given Gemfile"
+  echo "  -h          Show this help"
 }
 
 function parse_options()
 {
-	local OPTIND=1
-	local opt
-	while getopts "ECGr:w:j:g:h" opt; do
-		case "$opt" in
-		E)
-			SETUP_SOURCE=false
-			;;
-		C)
-			COMPILE=false
-			;;
-		G)
-			GEMFILE=
-			;;
-		r)
-			RUBY_VERSION=$OPTARG
-			;;
-		w)
-			WORKDIR="$OPTARG"
-			OWNS_WORKDIR=false
-			;;
-		j)
-			CONCURRENCY=$OPTARG
-			;;
-		g)
-			GEMFILE="$OPTARG"
-			;;
-		h)
-			usage
-			exit
-			;;
-		*)
-			return 1
-			;;
-		esac
-	done
+  local OPTIND=1
+  local opt
+  while getopts "ECGr:w:j:g:h" opt; do
+    case "$opt" in
+    E)
+      SETUP_SOURCE=false
+      ;;
+    C)
+      COMPILE=false
+      ;;
+    G)
+      GEMFILE=
+      ;;
+    r)
+      RUBY_VERSION=$OPTARG
+      ;;
+    w)
+      WORKDIR="$OPTARG"
+      OWNS_WORKDIR=false
+      ;;
+    j)
+      CONCURRENCY=$OPTARG
+      ;;
+    g)
+      GEMFILE="$OPTARG"
+      ;;
+    h)
+      usage
+      exit
+      ;;
+    *)
+      return 1
+      ;;
+    esac
+  done
 
-	(( OPTIND -= 1 )) || true
-	shift $OPTIND || true
-	RUNTIME_DIR="$1"
-	OUTPUT_DIR="$2"
+  (( OPTIND -= 1 )) || true
+  shift $OPTIND || true
+  RUNTIME_DIR="$1"
+  OUTPUT_DIR="$2"
 
-	if [[ "$RUNTIME_DIR" = "" || "$OUTPUT_DIR" = "" ]]; then
-		usage
-		exit 1
-	fi
-	if [[ ! -e "$RUNTIME_DIR" ]]; then
-		echo "ERROR: $RUNTIME_DIR doesn't exist."
-		exit 1
-	fi
-	if [[ ! -e "$OUTPUT_DIR" ]]; then
-		echo "ERROR: $OUTPUT_DIR doesn't exist."
-		exit 1
-	fi
+  if [[ "$RUNTIME_DIR" = "" || "$OUTPUT_DIR" = "" ]]; then
+    usage
+    exit 1
+  fi
+  if [[ ! -e "$RUNTIME_DIR" ]]; then
+    echo "ERROR: $RUNTIME_DIR doesn't exist."
+    exit 1
+  fi
+  if [[ ! -e "$OUTPUT_DIR" ]]; then
+    echo "ERROR: $OUTPUT_DIR doesn't exist."
+    exit 1
+  fi
 }
 
 parse_options "$@"
 RUNTIME_DIR="`cd \"$RUNTIME_DIR\" && pwd`"
 OUTPUT_DIR="`cd \"$OUTPUT_DIR\" && pwd`"
 if [[ "$WORKDIR" = "" ]]; then
-	WORKDIR=`mktemp -d /tmp/traveling-ruby.XXXXXXXX`
+  WORKDIR=`mktemp -d /tmp/traveling-ruby.XXXXXXXX`
 elif [[ ! -e "$WORKDIR" ]]; then
-	echo "ERROR: working directory $WORKDIR doesn't exist."
-	exit 1
+  echo "ERROR: working directory $WORKDIR doesn't exist."
+  exit 1
 else
-	WORKDIR="`cd \"$WORKDIR\" && pwd`"
+  WORKDIR="`cd \"$WORKDIR\" && pwd`"
 fi
 TMPBUILDROOT="$WORKDIR/inst"
 if [[ "$GEMFILE" != "" ]]; then
-	GEMFILE="`absolute_path \"$GEMFILE\"`"
-	if [[ -d "$GEMFILE" ]]; then
-		GEMFILES=("$GEMFILE"/*/Gemfile)
-	else
-		GEMFILES=("$GEMFILE")
-	fi
+  GEMFILE="`absolute_path \"$GEMFILE\"`"
+  if [[ -d "$GEMFILE" ]]; then
+    GEMFILES=("$GEMFILE"/*/Gemfile)
+  else
+    GEMFILES=("$GEMFILE")
+  fi
 fi
 if [[ -e ~/.bundle/config ]]; then
-	echo "ERROR: ~/.bundle/config detected. Global Bundler configuration" \
-		"could conflict with this build script, so please remove" \
-		"~/.bundle/config first."
-	exit 1
+  echo "ERROR: ~/.bundle/config detected. Global Bundler configuration" \
+    "could conflict with this build script, so please remove" \
+    "~/.bundle/config first."
+  exit 1
 fi
 "$SELFDIR/internal/check_sdk"
 
@@ -219,38 +219,33 @@ fi
 
 
 if [[ ! -e "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz" ]]; then
-	header "Downloading Ruby source code..."
-	RUBY_MAJOR=`echo $RUBY_VERSION | cut -d . -f 1`
-	RUBY_MINOR=`echo $RUBY_VERSION | cut -d . -f 2`
-	RUBY_MAJOR_MINOR="$RUBY_MAJOR.$RUBY_MINOR"
-	run rm -f "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz.tmp"
-	run curl --fail -L -o "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz.tmp" \
-		http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR_MINOR/ruby-$RUBY_VERSION.tar.gz
-	run mv "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz.tmp" "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz"
-	echo
+  header "Downloading Ruby source code..."
+  RUBY_MAJOR=`echo $RUBY_VERSION | cut -d . -f 1`
+  RUBY_MINOR=`echo $RUBY_VERSION | cut -d . -f 2`
+  RUBY_MAJOR_MINOR="$RUBY_MAJOR.$RUBY_MINOR"
+  run rm -f "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz.tmp"
+  run curl --fail -L -o "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz.tmp" \
+    http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR_MINOR/ruby-$RUBY_VERSION.tar.gz
+  run mv "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz.tmp" "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz"
+  echo
 fi
 
 
 header "Preparing Ruby source code..."
 
-export PATH="$RUNTIME_DIR/bin:$PATH"
 export LIBRARY_PATH="$RUNTIME_DIR/lib"
 export DYLD_FALLBACK_LIBRARY_PATH="$RUNTIME_DIR/lib"
 export PKG_CONFIG_PATH="$RUNTIME_DIR/lib/pkgconfig:/usr/lib/pkgconfig"
-export CCACHE_DIR="$RUNTIME_DIR/ccache"
-export CCACHE_COMPRESS=1
-export CCACHE_COMPRESS_LEVEL=3
 export RUNTIME_DIR
 export TMPBUILDROOT
-export DEAD_STRIP=false
 export RUBYOPT=-r"$SELFDIR/internal/modify_rbconfig_while_building"
 
 echo "Entering working directory $WORKDIR"
 pushd "$WORKDIR" >/dev/null
 
 if $SETUP_SOURCE; then
-	run rm -rf "ruby-$RUBY_VERSION"
-	run tar xzf "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz"
+  run rm -rf "ruby-$RUBY_VERSION"
+  run tar xzf "$RUNTIME_DIR/ruby-$RUBY_VERSION.tar.gz"
 fi
 echo "Entering ruby-$RUBY_VERSION"
 pushd "ruby-$RUBY_VERSION" >/dev/null
@@ -258,33 +253,36 @@ echo
 
 
 if $SETUP_SOURCE; then
-	header "Configuring..."
-	./configure \
-		--prefix "$TMPBUILDROOT" \
-		--disable-install-doc \
-		--disable-install-rdoc \
-		--disable-install-capi \
-		--with-out-ext=tk,sdbm,gdbm,dbm,dl,coverage \
-		--with-openssl-dir="$RUNTIME_DIR"
-	echo
+  header "Configuring..."
+  env
+  ./configure \
+    --prefix "$TMPBUILDROOT" \
+    --disable-install-doc \
+    --disable-install-rdoc \
+    --disable-install-capi \
+    --with-out-ext=*dbm \
+    --without-gmp \
+    --with-openssl-dir="$RUNTIME_DIR"
+  echo
 fi
 
 
 if $COMPILE; then
-	header "Compiling..."
-	run make -j$CONCURRENCY Q= V=1 exts.mk
-	run make -j$CONCURRENCY Q= V=1
-	echo
+  header "Compiling..."
+  run make -j$CONCURRENCY Q= V=1 exts.mk
+  run make -j$CONCURRENCY Q= V=1
+  echo
 fi
 
 
 header "Installing to temporary build output directory..."
 (
-	shopt -s dotglob
-	run mkdir -p "$TMPBUILDROOT"
-	run rm -rf "$TMPBUILDROOT"/*
+  shopt -s dotglob
+  run mkdir -p "$TMPBUILDROOT"
+  run rm -rf "$TMPBUILDROOT"/*
 )
 [[ $? == 0 ]]
+ln -sf $RUNTIME_DIR/lib $WORKDIR/lib
 run make install-nodoc
 echo
 
@@ -322,52 +320,52 @@ cat "$SELFDIR/internal/rbconfig_patch.rb" >> "$TMPBUILDROOT/lib/ruby/$RUBY_COMPA
 run rm -rf lib/ruby/gems/$RUBY_COMPAT_VERSION/gems/{test-unit,rdoc}-*
 
 if [[ "$GEMFILE" != "" ]]; then
-	# Restore cached gems.
-	if [[ -e "$RUNTIME_DIR/vendor" ]]; then
-		run cp -pR "$RUNTIME_DIR/vendor" vendor
-	fi
+  # Restore cached gems.
+  if [[ -e "$RUNTIME_DIR/vendor" ]]; then
+    run cp -pR "$RUNTIME_DIR/vendor" vendor
+  fi
 
-	# Install Bundler, either from cache or directly.
-	if [[ -e "$RUNTIME_DIR/vendor/cache/bundler-$BUNDLER_VERSION.gem" ]]; then
-		run "$TMPBUILDROOT/bin/gem" install "$RUNTIME_DIR/vendor/cache/bundler-$BUNDLER_VERSION.gem" --no-document
-	else
-		run "$TMPBUILDROOT/bin/gem" install bundler -v $BUNDLER_VERSION --no-document
-		run mkdir -p "$RUNTIME_DIR/vendor/cache"
-		run cp "$TMPBUILDROOT"/lib/ruby/gems/$RUBY_COMPAT_VERSION/cache/bundler-$BUNDLER_VERSION.gem \
-			"$RUNTIME_DIR/vendor/cache/"
-	fi
+  # Install Bundler, either from cache or directly.
+  if [[ -e "$RUNTIME_DIR/vendor/cache/bundler-$BUNDLER_VERSION.gem" ]]; then
+    run "$TMPBUILDROOT/bin/gem" install "$RUNTIME_DIR/vendor/cache/bundler-$BUNDLER_VERSION.gem" --no-document
+  else
+    run "$TMPBUILDROOT/bin/gem" install bundler -v $BUNDLER_VERSION --no-document
+    run mkdir -p "$RUNTIME_DIR/vendor/cache"
+    run cp "$TMPBUILDROOT"/lib/ruby/gems/$RUBY_COMPAT_VERSION/cache/bundler-$BUNDLER_VERSION.gem \
+      "$RUNTIME_DIR/vendor/cache/"
+  fi
 
-	export BUNDLE_BUILD__NOKOGIRI=" "
-	export BUNDLE_BUILD__MYSQL2="--with-mysql_config"
-	export BUNDLE_BUILD__CHARLOCK_HOLMES="--with-icu-dir=$RUNTIME_DIR"
+  export BUNDLE_BUILD__NOKOGIRI=" "
+  export BUNDLE_BUILD__MYSQL2="--with-mysql_config"
+  export BUNDLE_BUILD__CHARLOCK_HOLMES="--with-icu-dir=$RUNTIME_DIR"
 
-	# Run bundle install.
-	for GEMFILE in "${GEMFILES[@]}"; do
-		run cp "$GEMFILE" ./
-		if [[ -e "$GEMFILE.lock" ]]; then
-			run cp "$GEMFILE.lock" ./
-		fi
-		# We set -j to 1 because of this bug:
-		# https://github.com/bundler/bundler/issues/3660
-		# When it is solved, we can set -j to $CONCURRENCY.
-		run "$TMPBUILDROOT/bin/bundle" install --system --retry 3 --jobs 1
-		run "$TMPBUILDROOT/bin/bundle" package
+  # Run bundle install.
+  for GEMFILE in "${GEMFILES[@]}"; do
+    run cp "$GEMFILE" ./
+    if [[ -e "$GEMFILE.lock" ]]; then
+      run cp "$GEMFILE.lock" ./
+    fi
+    # We set -j to 1 because of this bug:
+    # https://github.com/bundler/bundler/issues/3660
+    # When it is solved, we can set -j to $CONCURRENCY.
+    run "$TMPBUILDROOT/bin/bundle" install --system --retry 3 --jobs 1
+    run "$TMPBUILDROOT/bin/bundle" package
 
-		# Cache gems.
-		run mkdir -p "$RUNTIME_DIR/vendor/cache"
-		run mv vendor/cache/* "$RUNTIME_DIR"/vendor/cache/
+    # Cache gems.
+    run mkdir -p "$RUNTIME_DIR/vendor/cache"
+    run mv vendor/cache/* "$RUNTIME_DIR"/vendor/cache/
 
-		run rm -rf Gemfile* .bundle
-	done
+    run rm -rf Gemfile* .bundle
+  done
 fi
 
 # Strip binaries and remove unnecessary files.
 run strip -S bin/ruby
 echo "Stripping libraries..."
 (
-	set -o pipefail
-	find . -name '*.bundle' | xargs strip -S
-	find . -name '*.dylib' | xargs strip -S
+  set -o pipefail
+  find . -name '*.bundle' | xargs strip -S
+  find . -name '*.dylib' | xargs strip -S
 )
 [[ $? == 0 ]]
 run rm bin/{erb,rdoc,ri}
@@ -382,11 +380,11 @@ run rm -rf lib/ruby/gems/$RUBY_COMPAT_VERSION/gems/*/{test,spec,*.md,*.rdoc}
 run rm -rf lib/ruby/gems/$RUBY_COMPAT_VERSION/gems/*/ext/*/*.{c,h}
 
 if [[ "$GEMFILE" != "" ]]; then
-	echo "Entering Bundler gem directory"
-	pushd lib/ruby/gems/$RUBY_COMPAT_VERSION/gems/bundler-$BUNDLER_VERSION >/dev/null
-	rm -rf .gitignore .rspec .travis.yml man Rakefile lib/bundler/man/*.txt lib/bundler/templates
-	popd >/dev/null
-	echo "Leaving Bundler gem directory"
+  echo "Entering Bundler gem directory"
+  pushd lib/ruby/gems/$RUBY_COMPAT_VERSION/gems/bundler-$BUNDLER_VERSION >/dev/null
+  rm -rf .gitignore .rspec .travis.yml man Rakefile lib/bundler/man/*.txt lib/bundler/templates
+  popd >/dev/null
+  echo "Leaving Bundler gem directory"
 fi
 
 # Create wrapper scripts.
@@ -399,8 +397,8 @@ run create_wrapper bin/gem gem true
 run create_wrapper bin/irb irb true
 run create_wrapper bin/rake rake true
 if $INSTALL_GEMS; then
-	run create_wrapper bin/bundle bundle true
-	run create_wrapper bin/bundler bundler true
+  run create_wrapper bin/bundle bundle true
+  run create_wrapper bin/bundler bundler true
 fi
 
 echo "Leaving $TMPBUILDROOT"
